
# 1. The URL (Delete the ?user=... part from the end of the URL and put sslmode=require)
spring.datasource.url=jdbc:postgresql://ep-ancient-cell-amj3l3wb-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require

# 2. Your Username
spring.datasource.username=neondb_owner

# 3. Your Password (paste the real password Neon gave you here)
spring.datasource.password=${DB_PASSWORD}


# 4. Keep this line so it creates the tables
spring.jpa.hibernate.ddl-auto=update