# 1. The AWS RDS URL (Routing through our local SSH tunnel)
spring.datasource.url=spring.datasource.url=jdbc:postgresql://fitness-data-db.ci70ew0ko0zx.us-east-1.rds.amazonaws.com:5432/fitnessapp
# 2. Your Username
spring.datasource.username=postgres

# 3. Your Password 
# Keep using the environment variable?it's the professional way!
spring.datasource.password=${DB_PASSWORD}

# 4. Hibernate & Security settings
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

# 5. Recommended for RDS (Helps Hibernate detect the Postgres version correctly)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect